// Full 66-clause framework. Used as the authoritative list across all versions.
export interface ClauseDef {
  id: string; // c1..c66
  number: number;
  category: string;
  title: string;
}

export const CLAUSE_FRAMEWORK: ClauseDef[] = [
  { number: 1, category: "Term and Termination", title: "Term of Contract" },
  { number: 2, category: "Term and Termination", title: "Renewal and Extension Terms" },
  { number: 3, category: "Term and Termination", title: "Termination for Convenience" },
  { number: 4, category: "Term and Termination", title: "Termination for Cause" },
  { number: 5, category: "Term and Termination", title: "Partial Termination" },
  { number: 6, category: "Term and Termination", title: "Exit Support and Obligations" },
  { number: 7, category: "Term and Termination", title: "Costs of Exit" },
  { number: 8, category: "Supplier Obligations", title: "Supplier Performance and Delivery Obligations" },
  { number: 9, category: "Supplier Obligations", title: "Service Scope" },
  { number: 10, category: "Supplier Obligations", title: "Service Levels" },
  { number: 11, category: "Supplier Obligations", title: "Service Credits" },
  { number: 12, category: "Buyer Remedies", title: "Reperformance" },
  { number: 13, category: "Buyer Remedies", title: "Remediation" },
  { number: 14, category: "Buyer Remedies", title: "Milestone Payments" },
  { number: 15, category: "Buyer Remedies", title: "Liquidated Damages" },
  { number: 16, category: "Buyer Remedies", title: "Step-In/Enhanced Cooperation" },
  { number: 17, category: "Warranties and Liability", title: "Warranties" },
  { number: 18, category: "Warranties and Liability", title: "Defect Liability Period" },
  { number: 19, category: "Restrictions", title: "Exclusivity" },
  { number: 20, category: "Warranties and Liability", title: "Parental Company Guarantee" },
  { number: 21, category: "Intellectual Property Rights (IPR)", title: "Ownership of IPR Created by the Supplier" },
  { number: 22, category: "Intellectual Property Rights (IPR)", title: "Ownership of Pre-existing IPR" },
  { number: 23, category: "Intellectual Property Rights (IPR)", title: "License/Rights to Use IPR Created by Supplier" },
  { number: 24, category: "Intellectual Property Rights (IPR)", title: "License/Rights to Use Any Buyer IPR" },
  { number: 25, category: "Commercial Terms", title: "Pricing, Pricing Model, and Rate Card Clarity" },
  { number: 26, category: "Commercial Terms", title: "Cost Increase/Decrease" },
  { number: 27, category: "Commercial Terms", title: "Cost Change - Non Index Linked Changes" },
  { number: 28, category: "Commercial Terms", title: "Minimum Volumes or Volume Commitments" },
  { number: 29, category: "Commercial Terms", title: "Minimum Revenue or Revenue Commitments" },
  { number: 30, category: "Commercial Terms", title: "Currency and FOREX Provisions" },
  { number: 31, category: "Commercial Terms", title: "Payment Terms" },
  { number: 32, category: "Commercial Terms", title: "Payment Dispute Terms" },
  { number: 33, category: "Commercial Terms", title: "Rebates and Discounts" },
  { number: 34, category: "Commercial Terms", title: "Mark-Up on Pass-Through Costs and Expenses" },
  { number: 35, category: "Limitation of Liability and Indemnities", title: "Liability Cap of Supplier" },
  { number: 36, category: "Limitation of Liability and Indemnities", title: "Unlimited Liabilities of Supplier" },
  { number: 37, category: "Limitation of Liability and Indemnities", title: "Recoverable Losses Against Supplier" },
  { number: 38, category: "Limitation of Liability and Indemnities", title: "Liability Cap of Buyer" },
  { number: 39, category: "Limitation of Liability and Indemnities", title: "Unlimited Liabilities of Buyer" },
  { number: 40, category: "Limitation of Liability and Indemnities", title: "Recoverable Losses Against Buyer" },
  { number: 41, category: "Limitation of Liability and Indemnities", title: "Indemnity in Favour of Supplier" },
  { number: 42, category: "Limitation of Liability and Indemnities", title: "Scope of Indemnity in Favour of Buyer" },
  { number: 43, category: "Limitation of Liability and Indemnities", title: "Exclusions or Other Restrictions on Buyer Recovery Under Indemnity" },
  { number: 44, category: "Limitation of Liability and Indemnities", title: "Indemnity in Favour of Buyer" },
  { number: 45, category: "Control and Compliance", title: "Acceptance" },
  { number: 46, category: "Control and Compliance", title: "Audit" },
  { number: 47, category: "Control and Compliance", title: "Confidentiality" },
  { number: 48, category: "Control and Compliance", title: "Data Processing" },
  { number: 49, category: "Control and Compliance", title: "Data Transfer" },
  { number: 50, category: "Control and Compliance", title: "Data Breach Notification" },
  { number: 51, category: "Control and Compliance", title: "Governance and Escalation" },
  { number: 52, category: "Control and Compliance", title: "Benchmarking" },
  { number: 53, category: "Control and Compliance", title: "Business Continuity and Disaster Recovery" },
  { number: 54, category: "Control and Compliance", title: "Key Personnel" },
  { number: 55, category: "Miscellaneous", title: "Choice of Law and Jurisdiction" },
  { number: 56, category: "Miscellaneous", title: "Dispute Resolution" },
  { number: 57, category: "Restrictions", title: "Use by Buyer Affiliates" },
  { number: 58, category: "Restrictions", title: "Subcontracting" },
  { number: 59, category: "Software", title: "Length and Type of License Provided" },
  { number: 60, category: "Software", title: "Support and Maintenance Terms" },
  { number: 61, category: "Software", title: "Upgrades and Upgrade Obligations" },
  { number: 62, category: "Software", title: "Uptime and Downtime Commitments" },
  { number: 63, category: "Software", title: "License Renewal Terms" },
  { number: 64, category: "Commercial Mechanics", title: "Gainshare Mechanism" },
  { number: 65, category: "Commercial Mechanics", title: "Inflation/CPI Clauses, Real Living Wage, National Insurance Uplift Terms" },
  { number: 66, category: "Commercial Mechanics", title: "Rate Card Clarity (Historic vs Post-Separation)" },
].map((c) => ({ ...c, id: `c${c.number}` }));

export const FRAMEWORK_BY_ID = new Map(CLAUSE_FRAMEWORK.map((c) => [c.id, c]));
