import type { ClauseResult, ContractVersion } from "./workflow-types";

/**
 * Curated Design option 3 table used by the v6a first-analysis prototype.
 *
 * The source workbook remains available through SWITCHED_ON_FIRST_ANALYSIS_VERSION;
 * this fixture mirrors the stakeholder review slice shown in the design reference.
 */
const DESIGN_OPTION_3_CLAUSES: ClauseResult[] = [
  {
    id: "c31",
    title: "Payment terms",
    subclause: "§31",
    category: "Commercial",
    severity: "high",
    sourceDeviationLevel: "High",
    resolved: false,
    change: "unchanged",
    deviation: "Supplier shall issue invoices monthly in arrears. Buyer shall pay all undisputed invoices within forty-five (45) days of receipt.",
    excerpt: "Supplier shall issue invoices monthly in arrears. Buyer shall pay all undisputed invoices within forty-five (45) days of receipt.",
    actionability: "Amend payment terms to 30 days from receipt of a valid, undisputed invoice.",
    rationale: "Payment terms are shorter than the buyer's preferred cash-flow position and should be amended before the contract is agreed.",
  },
  {
    id: "c35",
    title: "Limitation of liability — aggregate cap",
    subclause: "§35",
    category: "Risk",
    severity: "high",
    sourceDeviationLevel: "High",
    resolved: false,
    change: "unchanged",
    deviation: "Supplier's total aggregate liability under this Agreement shall not exceed the fees paid by Buyer in the three (3) months preceding the claim.",
    excerpt: "Supplier's total aggregate liability under this Agreement shall not exceed the fees paid by Buyer in the three (3) months preceding the claim.",
    actionability: "Increase aggregate liability cap to 150% of annual contract value, with carve-outs for confidentiality, IP infringement and data protection breaches.",
    rationale: "A three-month fee cap is materially below the preferred benchmark and leaves the buyer exposed to significant service, confidentiality, and IP risk.",
  },
  {
    id: "c3",
    title: "Termination for convenience",
    subclause: "§3",
    category: "Exit",
    severity: "medium",
    sourceDeviationLevel: "Medium",
    resolved: false,
    change: "unchanged",
    deviation: "Either party may terminate this Agreement for convenience upon one hundred and eighty (180) days' written notice.",
    excerpt: "Either party may terminate this Agreement for convenience upon one hundred and eighty (180) days' written notice.",
    actionability: "Reduce Buyer's termination-for-convenience notice to 90 days; retain 180 days for Supplier.",
    rationale: "The current notice period limits the buyer's ability to exit an underperforming arrangement within a commercially workable timeframe.",
  },
  {
    id: "c48",
    title: "Data protection — sub-processor consent",
    subclause: "§48",
    category: "Data",
    severity: "high",
    sourceDeviationLevel: "High",
    resolved: false,
    change: "new",
    missingClause: true,
    deviation: "No wording in the supplier's contract — this term should be negotiated in.",
    excerpt: "No wording in the supplier's contract — this term should be negotiated in.",
    actionability: "Add a clause requiring Supplier to obtain Buyer's prior written consent before engaging any new sub-processor, with a right to object.",
    rationale: "The contract lacks the required control over sub-processors, creating an avoidable data-protection and governance gap.",
  },
  {
    id: "c46",
    title: "Audit rights",
    subclause: "§46",
    category: "Governance",
    severity: "medium",
    sourceDeviationLevel: "Medium",
    resolved: false,
    change: "unchanged",
    deviation: "Buyer may audit Supplier's records once per calendar year on sixty (60) days' notice, at Buyer's cost.",
    excerpt: "Buyer may audit Supplier's records once per calendar year on sixty (60) days' notice, at Buyer's cost.",
    actionability: "Reduce audit notice to 30 days, allow twice-yearly audits where cause is shown, and shift audit cost to Supplier where material findings are identified.",
    rationale: "The audit right is too infrequent and slow to provide effective assurance when a material compliance concern arises.",
  },
  {
    id: "c11",
    title: "Service credits regime",
    subclause: "§11",
    category: "Performance",
    severity: "high",
    sourceDeviationLevel: "High",
    resolved: false,
    change: "new",
    missingClause: true,
    deviation: "No wording in the supplier's contract — this term should be negotiated in.",
    excerpt: "No wording in the supplier's contract — this term should be negotiated in.",
    actionability: "Introduce service credits of 5% of monthly charges per SLA breach, capped at 25% of monthly charges, non-exclusive of other remedies.",
    rationale: "Without a service-credit mechanism, the buyer has no defined commercial remedy when the supplier misses agreed service levels.",
  },
  {
    id: "c21",
    title: "Intellectual property — foreground IP",
    subclause: "§21",
    category: "IP",
    severity: "medium",
    sourceDeviationLevel: "Medium",
    resolved: false,
    change: "unchanged",
    deviation: "All intellectual property created by Supplier in the performance of the Services shall vest in Supplier, with a perpetual, royalty-free licence granted to Buyer.",
    excerpt: "All intellectual property created by Supplier in the performance of the Services shall vest in Supplier, with a perpetual, royalty-free licence granted to Buyer.",
    actionability: "Assign all foreground IP created specifically for Buyer to Buyer, with a licence-back to Supplier for internal use only.",
    rationale: "Supplier ownership of buyer-funded foreground IP reduces the buyer's control over assets created specifically for this engagement.",
  },
  {
    id: "c17",
    title: "Insurance — public liability",
    subclause: "§17",
    category: "Risk",
    severity: "low",
    sourceDeviationLevel: "Low",
    resolved: false,
    change: "unchanged",
    deviation: "Supplier shall maintain public liability insurance of not less than £5,000,000 per claim.",
    excerpt: "Supplier shall maintain public liability insurance of not less than £5,000,000 per claim.",
    actionability: "Increase minimum public liability cover to £10,000,000 per claim, unlimited in the aggregate.",
    rationale: "The existing insurance threshold is below the buyer's risk appetite for the potential scale of third-party claims.",
  },
  {
    id: "c55",
    title: "Notice period — contractual notices",
    subclause: "§55",
    category: "Governance",
    severity: "low",
    sourceDeviationLevel: "Low",
    resolved: false,
    change: "unchanged",
    deviation: "All notices shall be given in writing and delivered by pre-paid first-class post to the registered office.",
    excerpt: "All notices shall be given in writing and delivered by pre-paid first-class post to the registered office.",
    actionability: "Permit notices by email to nominated addresses in addition to post; deem received 24 hours after sending.",
    rationale: "Post-only notices slow down operational communication and create unnecessary uncertainty about when critical notices take effect.",
  },
  {
    id: "c27",
    title: "Change control procedure",
    subclause: "§27",
    category: "Governance",
    severity: "low",
    sourceDeviationLevel: "Low",
    resolved: false,
    change: "unchanged",
    deviation: "Any change to the scope or charges shall require a signed Change Request executed by authorised signatories of both parties.",
    excerpt: "Any change to the scope or charges shall require a signed Change Request executed by authorised signatories of both parties.",
    actionability: "Retain signature requirement but add a 10-business-day response SLA on Supplier for costed impact assessments.",
    rationale: "The signature control is appropriate, but the absence of a response commitment can delay commercially necessary changes.",
  },
  {
    id: "c47",
    title: "Confidentiality — survival period",
    subclause: "§47",
    category: "Risk",
    severity: "medium",
    sourceDeviationLevel: "Medium",
    resolved: false,
    change: "unchanged",
    deviation: "The confidentiality obligations in this clause shall survive termination for a period of three (3) years.",
    excerpt: "The confidentiality obligations in this clause shall survive termination for a period of three (3) years.",
    actionability: "Extend confidentiality survival to 7 years post-termination; indefinite for trade secrets and personal data.",
    rationale: "A three-year survival period does not adequately protect long-lived confidential information, trade secrets, or personal data.",
  },
  {
    id: "c56",
    title: "Governing law and jurisdiction",
    subclause: "§56",
    category: "Legal",
    severity: "low",
    sourceDeviationLevel: "Low",
    resolved: false,
    change: "unchanged",
    deviation: "This Agreement shall be governed by the laws of England and Wales. The parties submit to the non-exclusive jurisdiction of the English courts.",
    excerpt: "This Agreement shall be governed by the laws of England and Wales. The parties submit to the non-exclusive jurisdiction of the English courts.",
    actionability: "Change to exclusive jurisdiction of the English courts.",
    rationale: "Exclusive jurisdiction reduces the risk of parallel proceedings and gives the parties a clearer forum for resolving disputes.",
  },
  {
    id: "c50",
    title: "Data breach notification",
    subclause: "§50",
    category: "Data",
    severity: "low",
    sourceDeviationLevel: "None",
    resolved: true,
    change: "unchanged",
    deviation: "Supplier provides a defined data breach notification process aligned to the agreed control framework.",
    excerpt: "Supplier shall notify Buyer of a personal data breach without undue delay and provide ongoing updates.",
    actionability: "No immediate action required; retain the agreed notification process.",
    rationale: "The current notification commitment aligns with the agreed control framework and does not require a counter-position.",
  },
  {
    id: "c62",
    title: "Uptime and downtime commitments",
    subclause: "§62",
    category: "Performance",
    severity: "low",
    sourceDeviationLevel: "None",
    resolved: true,
    change: "unchanged",
    deviation: "Uptime and maintenance commitments align with the benchmark service schedule.",
    excerpt: "Supplier shall meet the agreed uptime target and provide advance notice of planned maintenance.",
    actionability: "No immediate action required; retain the agreed service schedule.",
    rationale: "The uptime and maintenance commitments align with the relevant service benchmark and require no further negotiation.",
  },
];

export const V6A_DESIGN_OPTION_3_FIRST_ANALYSIS_VERSION: ContractVersion = {
  version: "v1",
  uploadedAt: "2026-01-03T16:47:00",
  clauses: DESIGN_OPTION_3_CLAUSES,
  highIssues: DESIGN_OPTION_3_CLAUSES.filter((clause) => clause.severity === "high" && !clause.resolved).length,
  mediumIssues: DESIGN_OPTION_3_CLAUSES.filter((clause) => clause.severity === "medium" && !clause.resolved).length,
  lowIssues: DESIGN_OPTION_3_CLAUSES.filter((clause) => clause.severity === "low" && !clause.resolved).length,
  overallScore: 57,
};
